// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuleWebAPIPhatPT19.Data.Context;

#nullable disable

namespace MuleWebAPIPhatPT19.Data.Migrations
{
    [DbContext(typeof(mlsdb_phatpt19Context))]
    partial class mlsdb_phatpt19ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Account", b =>
                {
                    b.Property<string>("FldAccount")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("fldAccount");

                    b.Property<string>("FldPassword")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("fldPassword");

                    b.Property<string>("FldRole")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fldRole");

                    b.HasKey("FldAccount", "FldPassword")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly?>("CreatedByDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'2024-01-01'");

                    b.Property<string>("ProductName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<double?>("QuantityInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProductCode", "UnitPrice")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Purchaseorder", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'2024-01-01'");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly?>("CreatedByDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'2024-01-01'");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrderNo", "OrderDate")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("purchaseorders", (string)null);
                });

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Purchaseorderdetail", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("double");

                    b.Property<double?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.Property<double?>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("OrderNo", "ProductCode", "PurchasePrice")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.ToTable("purchaseorderdetails", (string)null);
                });

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Salesorder", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'2024-01-01'");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly?>("CreatedByDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("'2024-01-01'");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrderNo", "OrderDate")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("salesorders", (string)null);
                });

            modelBuilder.Entity("MuleWebAPIPhatPT19.Data.Models.Entities.Salesorderdetail", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<double>("SalesPrice")
                        .HasColumnType("double");

                    b.Property<double?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.Property<double?>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("OrderNo", "ProductCode", "SalesPrice")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.ToTable("salesorderdetails", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
